/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Cliente;
import java.awt.Color;

import Clases.UtilJavaflix;

import java.awt.Color;

import Clases.UtilJavaflix;
import Excepciones.EmailNoEncontrado;
import Excepciones.EmailNoValido;
import Excepciones.PasswordIncorrecta;
import javax.swing.JOptionPane;

/**
 *
 * @author Francisco
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        UtilJavaflix.cargarDatos();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelAcceso = new javax.swing.JPanel();
        jLabelJAVAFLIXAcceso = new javax.swing.JLabel();
        jLabelJAVAFLIXSombraAcceso = new javax.swing.JLabel();
        jLabelINICIARSESIONAcceso = new javax.swing.JLabel();
        jLabelFondoEtiquetasAcceso = new javax.swing.JLabel();
        jLabelDoblezAcceso = new javax.swing.JLabel();
        jPanelIntroDatosAcceso = new javax.swing.JPanel();
        jLabelCEAcceso = new javax.swing.JLabel();
        jTextFieldCEAcceso = new javax.swing.JTextField();
        jSeparatorCEAcceso = new javax.swing.JSeparator();
        jLabelClaveAcceso = new javax.swing.JLabel();
        jPasswordFieldClaveAcceso = new javax.swing.JPasswordField();
        jSeparatorClaveAcceso = new javax.swing.JSeparator();
        jPanelAccederAcceso = new javax.swing.JPanel();
        jLabelAccederbuttomAcceso = new javax.swing.JLabel();
        jLabelNotienescuentaAcceso = new javax.swing.JLabel();
        jPanelRegistrarseAcceso = new javax.swing.JPanel();
        jLabelRegistrarsebuttomAcceso = new javax.swing.JLabel();
        jLabelFondoAcceso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelAcceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelJAVAFLIXAcceso.setFont(new java.awt.Font("Roboto Black", 0, 100)); // NOI18N
        jLabelJAVAFLIXAcceso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJAVAFLIXAcceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJAVAFLIXAcceso.setText("JAVAFLIX");
        jPanelAcceso.add(jLabelJAVAFLIXAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 540, 130));

        jLabelJAVAFLIXSombraAcceso.setFont(new java.awt.Font("Roboto Black", 0, 100)); // NOI18N
        jLabelJAVAFLIXSombraAcceso.setForeground(new java.awt.Color(112, 101, 101));
        jLabelJAVAFLIXSombraAcceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJAVAFLIXSombraAcceso.setText("JAVAFLIX");
        jPanelAcceso.add(jLabelJAVAFLIXSombraAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 540, 130));

        jLabelINICIARSESIONAcceso.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jLabelINICIARSESIONAcceso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelINICIARSESIONAcceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelINICIARSESIONAcceso.setText("INICIAR SESIÓN");
        jPanelAcceso.add(jLabelINICIARSESIONAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 440, 120));

        jLabelFondoEtiquetasAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondoetiquetas.jpg"))); // NOI18N
        jLabelFondoEtiquetasAcceso.setText("jLabel7");
        jPanelAcceso.add(jLabelFondoEtiquetasAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 440, 120));

        jLabelDoblezAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/doblez.jpg"))); // NOI18N
        jPanelAcceso.add(jLabelDoblezAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 30, -1));

        jPanelIntroDatosAcceso.setBackground(new java.awt.Color(255, 255, 255));
        jPanelIntroDatosAcceso.setMinimumSize(new java.awt.Dimension(360, 520));
        jPanelIntroDatosAcceso.setName(""); // NOI18N
        jPanelIntroDatosAcceso.setPreferredSize(new java.awt.Dimension(360, 582));
        jPanelIntroDatosAcceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCEAcceso.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelCEAcceso.setText("CORREO ELECTRÓNICO");
        jPanelIntroDatosAcceso.add(jLabelCEAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jTextFieldCEAcceso.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jTextFieldCEAcceso.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldCEAcceso.setText("Escriba su correo electrónico");
        jTextFieldCEAcceso.setToolTipText("");
        jTextFieldCEAcceso.setBorder(null);
        jTextFieldCEAcceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldCEAccesoMousePressed(evt);
            }
        });
        jTextFieldCEAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCEAccesoActionPerformed(evt);
            }
        });
        jPanelIntroDatosAcceso.add(jTextFieldCEAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 300, -1));
        jPanelIntroDatosAcceso.add(jSeparatorCEAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 310, 18));

        jLabelClaveAcceso.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelClaveAcceso.setText("CLAVE");
        jPanelIntroDatosAcceso.add(jLabelClaveAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jPasswordFieldClaveAcceso.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordFieldClaveAcceso.setText("**********");
        jPasswordFieldClaveAcceso.setToolTipText("");
        jPasswordFieldClaveAcceso.setBorder(null);
        jPasswordFieldClaveAcceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFieldClaveAccesoMousePressed(evt);
            }
        });
        jPanelIntroDatosAcceso.add(jPasswordFieldClaveAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 290, -1));
        jPanelIntroDatosAcceso.add(jSeparatorClaveAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 310, 20));

        jPanelAccederAcceso.setBackground(new java.awt.Color(180, 45, 49));
        jPanelAccederAcceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelAccederbuttomAcceso.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabelAccederbuttomAcceso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAccederbuttomAcceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAccederbuttomAcceso.setText("ACCEDER");
        jLabelAccederbuttomAcceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAccederbuttomAcceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAccederbuttomAccesoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelAccederbuttomAccesoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelAccederbuttomAccesoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelAccederbuttomAccesoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelAccederbuttomAccesoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelAccederAccesoLayout = new javax.swing.GroupLayout(jPanelAccederAcceso);
        jPanelAccederAcceso.setLayout(jPanelAccederAccesoLayout);
        jPanelAccederAccesoLayout.setHorizontalGroup(
            jPanelAccederAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAccederbuttomAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanelAccederAccesoLayout.setVerticalGroup(
            jPanelAccederAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAccederbuttomAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        jPanelIntroDatosAcceso.add(jPanelAccederAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 170, -1));

        jLabelNotienescuentaAcceso.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabelNotienescuentaAcceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNotienescuentaAcceso.setText("¿No tienes cuenta? Registrate");
        jPanelIntroDatosAcceso.add(jLabelNotienescuentaAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 410, -1));

        jPanelRegistrarseAcceso.setBackground(new java.awt.Color(180, 45, 49));
        jPanelRegistrarseAcceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelRegistrarseAcceso.setPreferredSize(new java.awt.Dimension(170, 62));
        jPanelRegistrarseAcceso.setRequestFocusEnabled(false);

        jLabelRegistrarsebuttomAcceso.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabelRegistrarsebuttomAcceso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrarsebuttomAcceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistrarsebuttomAcceso.setText("REGISTRASRE");
        jLabelRegistrarsebuttomAcceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegistrarsebuttomAcceso.setMaximumSize(new java.awt.Dimension(62, 17));
        jLabelRegistrarsebuttomAcceso.setMinimumSize(new java.awt.Dimension(62, 17));
        jLabelRegistrarsebuttomAcceso.setName(""); // NOI18N
        jLabelRegistrarsebuttomAcceso.setPreferredSize(new java.awt.Dimension(62, 17));
        jLabelRegistrarsebuttomAcceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistrarsebuttomAccesoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRegistrarsebuttomAccesoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRegistrarsebuttomAccesoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistrarseAccesoLayout = new javax.swing.GroupLayout(jPanelRegistrarseAcceso);
        jPanelRegistrarseAcceso.setLayout(jPanelRegistrarseAccesoLayout);
        jPanelRegistrarseAccesoLayout.setHorizontalGroup(
            jPanelRegistrarseAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRegistrarsebuttomAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanelRegistrarseAccesoLayout.setVerticalGroup(
            jPanelRegistrarseAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRegistrarsebuttomAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        jPanelIntroDatosAcceso.add(jPanelRegistrarseAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 170, -1));

        jPanelAcceso.add(jPanelIntroDatosAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 410, 640));

        jLabelFondoAcceso.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondoAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/palomitasbienrojo.jpg"))); // NOI18N
        jLabelFondoAcceso.setText("jLabel2");
        jPanelAcceso.add(jLabelFondoAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1239, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 1239, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelAccederbuttomAccesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccederbuttomAccesoMouseClicked
        // TODO add your handling code here:
        try {
            UtilJavaflix.validarEmail(jTextFieldCEAcceso.getText());
            Cliente cliente_logeado = UtilJavaflix.iniciarSesion(jTextFieldCEAcceso.getText(),String.valueOf(jPasswordFieldClaveAcceso.getPassword()));
            JOptionPane.showMessageDialog(rootPane, "Bienvenido,"+cliente_logeado.getNombre() , "Inicio de sesion correcto", JOptionPane.INFORMATION_MESSAGE);
        } catch (EmailNoValido | EmailNoEncontrado | PasswordIncorrecta ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabelAccederbuttomAccesoMouseClicked

    private void jTextFieldCEAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCEAccesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCEAccesoActionPerformed

    private void jLabelRegistrarsebuttomAccesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrarsebuttomAccesoMouseClicked
        this.setVisible(false);
        registroUsuario registro = new registroUsuario(this);
        registro.setVisible(true);
    }//GEN-LAST:event_jLabelRegistrarsebuttomAccesoMouseClicked

    private void jLabelAccederbuttomAccesoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccederbuttomAccesoMouseEntered
        // TODO add your handling code here:   
        jPanelAccederAcceso.setBackground(new Color(148, 13, 30));
    }//GEN-LAST:event_jLabelAccederbuttomAccesoMouseEntered

    private void jLabelAccederbuttomAccesoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccederbuttomAccesoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelAccederbuttomAccesoMouseReleased

    private void jLabelAccederbuttomAccesoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccederbuttomAccesoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelAccederbuttomAccesoMousePressed

    private void jLabelAccederbuttomAccesoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAccederbuttomAccesoMouseExited
        // TODO add your handling code here:
        jPanelAccederAcceso.setBackground(new Color(180, 45, 49));
    }//GEN-LAST:event_jLabelAccederbuttomAccesoMouseExited

    private void jLabelRegistrarsebuttomAccesoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrarsebuttomAccesoMouseEntered
        // TODO add your handling code here:
        jPanelRegistrarseAcceso.setBackground(new Color(148, 13, 30));
    }//GEN-LAST:event_jLabelRegistrarsebuttomAccesoMouseEntered

    private void jLabelRegistrarsebuttomAccesoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistrarsebuttomAccesoMouseExited
        // TODO add your handling code here:
        jPanelRegistrarseAcceso.setBackground(new Color(180, 45, 49));
    }//GEN-LAST:event_jLabelRegistrarsebuttomAccesoMouseExited

    private void jTextFieldCEAccesoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCEAccesoMousePressed
        // TODO add your handling code here:
        if (jTextFieldCEAcceso.getText().equals("Escriba su correo electrónico")) {
            jTextFieldCEAcceso.setText("");
            jTextFieldCEAcceso.setForeground(Color.black);
        }
        if (String.valueOf(jPasswordFieldClaveAcceso.getPassword()).isEmpty()) {
            jPasswordFieldClaveAcceso.setText("**********");
            jPasswordFieldClaveAcceso.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jTextFieldCEAccesoMousePressed

    private void jPasswordFieldClaveAccesoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldClaveAccesoMousePressed
        // TODO add your handling code here:
        if (String.valueOf(jPasswordFieldClaveAcceso.getPassword()).equals("**********")) {
            jPasswordFieldClaveAcceso.setText("");
            jPasswordFieldClaveAcceso.setForeground(Color.black);
        }
        if (jTextFieldCEAcceso.getText().isEmpty()) {
            jTextFieldCEAcceso.setText("Escriba su correo electrónico");
            jTextFieldCEAcceso.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPasswordFieldClaveAccesoMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and djLabelINICIARSESIONthe form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelAccederbuttomAcceso;
    private javax.swing.JLabel jLabelCEAcceso;
    private javax.swing.JLabel jLabelClaveAcceso;
    private javax.swing.JLabel jLabelDoblezAcceso;
    private javax.swing.JLabel jLabelFondoAcceso;
    private javax.swing.JLabel jLabelFondoEtiquetasAcceso;
    private javax.swing.JLabel jLabelINICIARSESIONAcceso;
    private javax.swing.JLabel jLabelJAVAFLIXAcceso;
    private javax.swing.JLabel jLabelJAVAFLIXSombraAcceso;
    private javax.swing.JLabel jLabelNotienescuentaAcceso;
    private javax.swing.JLabel jLabelRegistrarsebuttomAcceso;
    private javax.swing.JPanel jPanelAccederAcceso;
    private javax.swing.JPanel jPanelAcceso;
    private javax.swing.JPanel jPanelIntroDatosAcceso;
    private javax.swing.JPanel jPanelRegistrarseAcceso;
    private javax.swing.JPasswordField jPasswordFieldClaveAcceso;
    private javax.swing.JSeparator jSeparatorCEAcceso;
    private javax.swing.JSeparator jSeparatorClaveAcceso;
    private javax.swing.JTextField jTextFieldCEAcceso;
    // End of variables declaration//GEN-END:variables
}
